-- AfricaTravel - Master Seed Data for Supabase PostgreSQL

INSERT INTO "system_settings" ("id", "data", "updatedAt") VALUES ('default', "{\"profile\":{\"name\":\"Mohamed Raafat\",\"fullName\":\"Mohamed Raafat\",\"email\":\"admin@africatravel.com\",\"role\":\"Senior Operations Director\",\"title\":\"Senior Operations Director\",\"phone\":\"+20 100 000 1122\"},\"company\":{\"name\":\"AfricaTravel Travel Operations Ltd.\",\"iataNumber\":\"12-3 4567 8\",\"taxId\":\"EG-904-881-229\",\"baseCurrency\":\"EGP\",\"address\":\"14 Al-Thawra Street, Heliopolis, Cairo, Egypt\",\"phone\":\"+20 2 2415 8800\"},\"currencies\":[\"EGP\",\"USD\",\"EUR\",\"SAR\",\"AED\"],\"paymentMethods\":[\"Cash\",\"Credit Card\",\"Bank Transfer\",\"Vodafone Cash\",\"InstaPay\",\"Corporate Account\"],\"ticketStatuses\":[\"CONFIRMED\",\"PENDING PAY\",\"PARTIALLY PAID\",\"PAID\",\"MODIFIED\",\"REFUNDED\",\"CANCELLED\"],\"notifications\":{\"emailOnNewTicket\":true,\"emailOnRefundRequest\":true,\"emailOnFlightDelay\":true,\"dailySummaryReport\":true}}"::jsonb, NOW()) ON CONFLICT ("id") DO UPDATE SET "data" = EXCLUDED."data";

-- Users (Note: passwordHash is set to disabled placeholder; bootstrap accounts with BOOTSTRAP_ADMIN_PASSWORD=... node prisma/generate-sql.js)
INSERT INTO "users" ("id", "name", "email", "role", "title", "passwordHash", "status", "lastActive", "createdAt", "updatedAt") VALUES ('EMP-101', 'Mohamed Raafat', 'admin@africatravel.com', 'ADMIN', 'Senior Operations Director', '!DISABLED_ACCOUNT_BOOTSTRAP_REQUIRED!', 'ACTIVE', 'Just now', NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "passwordHash" = EXCLUDED."passwordHash";
INSERT INTO "users" ("id", "name", "email", "role", "title", "passwordHash", "status", "lastActive", "createdAt", "updatedAt") VALUES ('EMP-102', 'Ahmed Raafat', 'ahmed.r@africatravel.com', 'ADMIN', 'Senior Operations Manager', '!DISABLED_ACCOUNT_BOOTSTRAP_REQUIRED!', 'ACTIVE', 'Just now', NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "passwordHash" = EXCLUDED."passwordHash";
INSERT INTO "users" ("id", "name", "email", "role", "title", "passwordHash", "status", "lastActive", "createdAt", "updatedAt") VALUES ('EMP-103', 'Nour Wael', 'nour.w@africatravel.com', 'AGENT', 'Ticketing Officer', '!DISABLED_ACCOUNT_BOOTSTRAP_REQUIRED!', 'ACTIVE', 'Just now', NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "passwordHash" = EXCLUDED."passwordHash";
INSERT INTO "users" ("id", "name", "email", "role", "title", "passwordHash", "status", "lastActive", "createdAt", "updatedAt") VALUES ('EMP-104', 'Hashem Ahmed', 'hashem.a@africatravel.com', 'AGENT', 'Customer Operations Specialist', '!DISABLED_ACCOUNT_BOOTSTRAP_REQUIRED!', 'ACTIVE', 'Just now', NOW(), NOW()) ON CONFLICT ("id") DO UPDATE SET "name" = EXCLUDED."name", "email" = EXCLUDED."email", "passwordHash" = EXCLUDED."passwordHash";

INSERT INTO "customers" ("id", "name", "email", "phone", "passport", "nationality", "isVip", "memberSince", "createdAt", "updatedAt") VALUES ('CUST-8924', 'Ahmed Mohamed', 'ahmed.m@example.com', '+20 100 123 4567', 'A12345678', 'Egyptian (EGY)', true, '2021', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "customers" ("id", "name", "email", "phone", "passport", "nationality", "isVip", "memberSince", "createdAt", "updatedAt") VALUES ('CUST-8925', 'Nourhan Adel', 'nourhan.adel@example.com', '+20 111 987 6543', 'A98765432', 'Egyptian (EGY)', false, '2022', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "customers" ("id", "name", "email", "phone", "passport", "nationality", "isVip", "memberSince", "createdAt", "updatedAt") VALUES ('CUST-8926', 'Tarek Mahmoud', 'tarek.m@example.com', '+20 122 345 6789', 'A55443322', 'Egyptian (EGY)', false, '2023', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "customers" ("id", "name", "email", "phone", "passport", "nationality", "isVip", "memberSince", "createdAt", "updatedAt") VALUES ('CUST-8927', 'Sarah Jenkins', 'sarah.j@globex.com', '+1 (555) 345-6789', 'P98472910', 'American (USA)', true, '2020', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "customers" ("id", "name", "email", "phone", "passport", "nationality", "isVip", "memberSince", "createdAt", "updatedAt") VALUES ('CUST-8928', 'Eleanor Vance', 'eleanor.v@example.com', '+44 20 7946 0912', 'GB8823419', 'British (GBR)', false, '2023', NOW(), NOW()) ON CONFLICT ("id") DO NOTHING;

INSERT INTO "tickets" ("id", "ticketNumber", "pnr", "customerId", "passengerName", "phone", "passport", "nationality", "dob", "email", "airline", "airlineCode", "flightNumber", "returnFlightNumber", "origin", "originTerminal", "originAirportName", "destination", "destinationTerminal", "destinationAirportName", "departureDate", "arrivalDate", "returnDepartureDate", "returnArrivalDate", "tripType", "flightDuration", "cabinClass", "seat", "baggage", "ticketPrice", "currency", "status", "createdBy", "createdById", "createdAt", "updatedAt") VALUES ('TK-10254', '077-1234567890', 'MSX92A', 'CUST-8924', 'Ahmed Mohamed', '+20 100 123 4567', 'A12345678', 'Egyptian (EGY)', '1985-05-15', 'ahmed.m@example.com', 'EgyptAir', 'MS', 'MS 901', 'MS 902', 'CAI', 'Terminal 3', 'Cairo International Airport', 'DXB', 'Terminal 1', 'Dubai International Airport', '2023-10-24T10:30:00Z', '2023-10-24T15:45:00Z', '2023-11-02T18:00:00Z', '2023-11-02T20:15:00Z', 'Round Trip', '3h 15m', 'Economy (Y)', '14B', '2 x 23kg', 18500, 'EGP', 'CONFIRMED', 'Sarah Jenkins', 'EMP-102', '2023-10-12T14:32:00Z', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "payments" ("id", "ticketId", "amount", "currency", "method", "reference", "date", "addedBy", "notes", "createdAt") VALUES ('PAY-701', 'TK-10254', 10000, 'EGP', 'Bank Transfer', 'TRX-CIB-9021', '2023-10-12T14:40:00Z', 'Sarah Jenkins', 'Initial booking deposit', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "payments" ("id", "ticketId", "amount", "currency", "method", "reference", "date", "addedBy", "notes", "createdAt") VALUES ('PAY-702', 'TK-10254', 8500, 'EGP', 'Credit Card', 'AUTH-VISA-4491', '2023-10-18T10:15:00Z', 'Ahmed Hassan', 'Final settlement payment', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "modifications" ("id", "ticketId", "title", "originalFlight", "newFlight", "changeFee", "currency", "reason", "requestedBy", "processedBy", "date", "status", "createdAt") VALUES ('MOD-301', 'TK-10254', 'Modification #1', '{"flightNumber":"MS 912","date":"2023-11-12T10:00:00Z","route":"Cairo (CAI) → Dubai (DXB)","duration":"3h 20m"}'::jsonb, '{"flightNumber":"MS 914","date":"2023-11-13T14:45:00Z","route":"Cairo (CAI) → Dubai (DXB)","note":"+1 Day, +4h 45m"}'::jsonb, 1200, 'EGP', 'Client requested later departure due to business meeting.', 'Ahmed Mohamed', 'Sarah Jenkins', '2023-10-24T14:30:00Z', 'COMPLETED', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "tickets" ("id", "ticketNumber", "pnr", "customerId", "passengerName", "phone", "passport", "nationality", "dob", "email", "airline", "airlineCode", "flightNumber", "returnFlightNumber", "origin", "originTerminal", "originAirportName", "destination", "destinationTerminal", "destinationAirportName", "departureDate", "arrivalDate", "returnDepartureDate", "returnArrivalDate", "tripType", "flightDuration", "cabinClass", "seat", "baggage", "ticketPrice", "currency", "status", "createdBy", "createdById", "createdAt", "updatedAt") VALUES ('TK-10253', '176-9876543210', 'EK4B2C', 'CUST-8925', 'Nourhan Adel', '+20 111 987 6543', 'A98765432', 'Egyptian (EGY)', '1992-08-20', 'nourhan.adel@example.com', 'Emirates', 'EK', 'EK 924', NULL, 'CAI', 'Terminal 2', 'Cairo International Airport', 'DXB', 'Terminal 3', 'Dubai International Airport', '2023-10-25T14:15:00Z', '2023-10-25T19:30:00Z', NULL, NULL, 'One Way', '3h 15m', 'Business (J)', '03A', '2 x 32kg', 22000, 'EGP', 'PARTIALLY PAID', 'Marcus Reed', 'EMP-103', '2023-10-23T11:20:00Z', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "payments" ("id", "ticketId", "amount", "currency", "method", "reference", "date", "addedBy", "notes", "createdAt") VALUES ('PAY-703', 'TK-10253', 10000, 'EGP', 'Cash', 'RCP-88910', '2023-10-23T11:25:00Z', 'Marcus Reed', 'Deposit received in branch', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "tickets" ("id", "ticketNumber", "pnr", "customerId", "passengerName", "phone", "passport", "nationality", "dob", "email", "airline", "airlineCode", "flightNumber", "returnFlightNumber", "origin", "originTerminal", "originAirportName", "destination", "destinationTerminal", "destinationAirportName", "departureDate", "arrivalDate", "returnDepartureDate", "returnArrivalDate", "tripType", "flightDuration", "cabinClass", "seat", "baggage", "ticketPrice", "currency", "status", "createdBy", "createdById", "createdAt", "updatedAt") VALUES ('TK-10252', '077-4561237890', 'MS2P9Z', 'CUST-8926', 'Tarek Mahmoud', '+20 122 345 6789', 'A55443322', 'Egyptian (EGY)', '1979-11-03', 'tarek.m@example.com', 'EgyptAir', 'MS', 'MS 671', NULL, 'CAI', 'Terminal 3', 'Cairo International Airport', 'JED', 'Terminal 1', 'King Abdulaziz International Airport', '2023-10-10T08:00:00Z', '2023-10-10T10:15:00Z', NULL, NULL, 'One Way', '2h 15m', 'Economy (Y)', '22C', '1 x 23kg', 8500, 'EGP', 'CANCELLED', 'Ahmed Hassan', 'EMP-101', '2023-10-05T09:10:00Z', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "payments" ("id", "ticketId", "amount", "currency", "method", "reference", "date", "addedBy", "notes", "createdAt") VALUES ('PAY-704', 'TK-10252', 8500, 'EGP', 'Vodafone Cash', 'VF-4482910', '2023-10-05T09:15:00Z', 'Ahmed Hassan', 'Online wallet full payment', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "refunds" ("id", "ticketId", "originalAmount", "totalPaid", "amount", "currency", "reason", "status", "requestedDate", "processedDate", "processedBy", "createdAt") VALUES ('RF-9021', 'TK-10252', 8500, 8500, 8500, 'EGP', 'Medical Emergency — Hospitalization certificate provided.', 'COMPLETED', '2023-10-08T11:00:00Z', '2023-10-09T15:30:00Z', 'Sarah Jenkins', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "tickets" ("id", "ticketNumber", "pnr", "customerId", "passengerName", "phone", "passport", "nationality", "dob", "email", "airline", "airlineCode", "flightNumber", "returnFlightNumber", "origin", "originTerminal", "originAirportName", "destination", "destinationTerminal", "destinationAirportName", "departureDate", "arrivalDate", "returnDepartureDate", "returnArrivalDate", "tripType", "flightDuration", "cabinClass", "seat", "baggage", "ticketPrice", "currency", "status", "createdBy", "createdById", "createdAt", "updatedAt") VALUES ('TK-10251', '157-8899223344', 'QR981L', 'CUST-8927', 'Sarah Jenkins', '+1 (555) 345-6789', 'P98472910', 'American (USA)', '1988-03-24', 'sarah.j@globex.com', 'Qatar Airways', 'QR', 'QR 1302', NULL, 'CAI', 'Terminal 2', 'Cairo International Airport', 'DOH', 'Terminal 1', 'Hamad International Airport', '2023-11-05T19:00:00Z', '2023-11-05T23:15:00Z', NULL, NULL, 'One Way', '3h 15m', 'First (F)', '01A', '3 x 32kg', 38000, 'EGP', 'CONFIRMED', 'Ahmed Hassan', 'EMP-101', '2023-10-20T16:00:00Z', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "payments" ("id", "ticketId", "amount", "currency", "method", "reference", "date", "addedBy", "notes", "createdAt") VALUES ('PAY-705', 'TK-10251', 38000, 'EGP', 'Corporate Account', 'CORP-GLBX-091', '2023-10-20T16:05:00Z', 'Ahmed Hassan', 'Billed to Globex Inc master account', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "tickets" ("id", "ticketNumber", "pnr", "customerId", "passengerName", "phone", "passport", "nationality", "dob", "email", "airline", "airlineCode", "flightNumber", "returnFlightNumber", "origin", "originTerminal", "originAirportName", "destination", "destinationTerminal", "destinationAirportName", "departureDate", "arrivalDate", "returnDepartureDate", "returnArrivalDate", "tripType", "flightDuration", "cabinClass", "seat", "baggage", "ticketPrice", "currency", "status", "createdBy", "createdById", "createdAt", "updatedAt") VALUES ('TK-9824', '006-7788990011', 'DL442A', 'CUST-8928', 'Eleanor Vance', '+44 20 7946 0912', 'GB8823419', 'British (GBR)', '1990-12-10', 'eleanor.v@example.com', 'British Airways', 'BA', 'BA 178', NULL, 'JFK', 'Terminal 7', 'John F. Kennedy International Airport', 'LHR', 'Terminal 5', 'London Heathrow Airport', '2023-10-27T08:30:00Z', '2023-10-27T20:15:00Z', NULL, NULL, 'One Way', '6h 45m', 'Economy (Y)', '12A', '1 x 23kg', 1250, 'USD', 'PARTIALLY PAID', 'Sarah Jenkins', 'EMP-102', '2023-10-22T09:30:00Z', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "payments" ("id", "ticketId", "amount", "currency", "method", "reference", "date", "addedBy", "notes", "createdAt") VALUES ('PAY-706', 'TK-9824', 800, 'USD', 'Credit Card (Stripe)', 'ch_3M49819284', '2023-10-22T09:35:00Z', 'Sarah Jenkins', 'Deposit paid via phone authorization', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "audit_logs" ("id", "timestamp", "user", "action", "ticketId", "customerId", "description", "createdAt") VALUES ('ACT-901', '2026-08-23T01:57:34.586Z', 'Ahmed Hassan', 'CREATE_TICKET', 'TK-10254', 'CUST-8924', 'Created new round-trip booking CAI ✈ DXB for Ahmed Mohamed.', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "audit_logs" ("id", "timestamp", "user", "action", "ticketId", "customerId", "description", "createdAt") VALUES ('ACT-902', '2026-08-23T01:44:34.587Z', 'Mohamed Ali', 'ADD_PAYMENT', 'TK-10254', 'CUST-8924', 'Added payment of 8,500 EGP via Credit Card (AUTH-VISA-4491).', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "audit_logs" ("id", "timestamp", "user", "action", "ticketId", "customerId", "description", "createdAt") VALUES ('ACT-903', '2026-08-22T21:59:34.587Z', 'Sarah Jenkins', 'MODIFY_FLIGHT', 'TK-10254', 'CUST-8924', 'Modified departure schedule from Oct 24 to Nov 13 with 1,200 EGP change fee.', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "audit_logs" ("id", "timestamp", "user", "action", "ticketId", "customerId", "description", "createdAt") VALUES ('ACT-904', '2026-08-22T01:59:34.587Z', 'Lena Chen', 'UPDATE_CUSTOMER', NULL, 'CUST-8924', 'Updated customer passport expiration and dietary preferences.', NOW()) ON CONFLICT ("id") DO NOTHING;
INSERT INTO "audit_logs" ("id", "timestamp", "user", "action", "ticketId", "customerId", "description", "createdAt") VALUES ('ACT-905', '2026-08-21T13:59:34.587Z', 'Sarah Jenkins', 'COMPLETE_REFUND', 'TK-10252', 'CUST-8926', 'Completed medical cancellation refund of 8,500 EGP for Tarek Mahmoud.', NOW()) ON CONFLICT ("id") DO NOTHING;
